/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pi.Telas;

import pi.Telas.TelaInformativa;

/**
 *
 * @author jsant
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public TelaInicial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        colorLbl = new javax.swing.JLabel();
        weightLbl = new javax.swing.JLabel();
        hightLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        colorTF = new javax.swing.JTextField();
        hightTF = new javax.swing.JTextField();
        weightTF = new javax.swing.JTextField();
        nextScreenBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        jLabel1.setText("Make your animal");

        nameLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 14)); // NOI18N
        nameLbl.setText("Nome");

        colorLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 14)); // NOI18N
        colorLbl.setText("cor");

        weightLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 14)); // NOI18N
        weightLbl.setText("Peso");

        hightLbl.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 14)); // NOI18N
        hightLbl.setText("Altura");

        nameTF.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 14)); // NOI18N
        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        colorTF.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 14)); // NOI18N

        hightTF.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 14)); // NOI18N

        weightTF.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 14)); // NOI18N

        nextScreenBtn.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        nextScreenBtn.setText("Next");
        nextScreenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextScreenBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hightLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hightTF)
                        .addComponent(colorTF)
                        .addComponent(nameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addComponent(weightTF)))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(nextScreenBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hightLbl)
                    .addComponent(hightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightLbl)
                    .addComponent(weightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorLbl)
                    .addComponent(colorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(nextScreenBtn)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void nextScreenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextScreenBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaInformativa tela = new TelaInformativa();
        tela.setVisible(true);
        tela.setNameLbl(nameTF.getText());
        tela.setColorLbl(colorTF.getText());
        tela.setWeightLbl(weightTF.getText());
        tela.setHightLbl(hightTF.getText());
    }//GEN-LAST:event_nextScreenBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colorLbl;
    private javax.swing.JTextField colorTF;
    private javax.swing.JLabel hightLbl;
    private javax.swing.JTextField hightTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton nextScreenBtn;
    private javax.swing.JLabel weightLbl;
    private javax.swing.JTextField weightTF;
    // End of variables declaration//GEN-END:variables
}
