/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pi.Telas;

import javax.swing.JLabel;

/**
 *
 * @author jsant
 */
public class TelaInformativa extends javax.swing.JFrame{

    /**
     * Creates new form TelaInformativa
     */
    public TelaInformativa() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        colorLbl = new javax.swing.JLabel();
        weightLbl = new javax.swing.JLabel();
        hightLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLbl.setText("jLabel1");

        colorLbl.setText("jLabel2");

        weightLbl.setText("jLabel3");

        hightLbl.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hightLbl)
                    .addComponent(weightLbl)
                    .addComponent(colorLbl)
                    .addComponent(nameLbl))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(nameLbl)
                .addGap(32, 32, 32)
                .addComponent(colorLbl)
                .addGap(26, 26, 26)
                .addComponent(weightLbl)
                .addGap(29, 29, 29)
                .addComponent(hightLbl)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colorLbl;
    private javax.swing.JLabel hightLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel weightLbl;
    // End of variables declaration//GEN-END:variables

    public JLabel getColorLbl() {
        return colorLbl;
    }

    public void setColorLbl(String colorTxt) {
        this.colorLbl.setText(colorTxt);
    }

    public JLabel getHightLbl() {
        return hightLbl;
    }

    public void setHightLbl(String hightTxt) {
        this.hightLbl.setText(hightTxt);
    }

    public JLabel getNameLbl() {
        return nameLbl;
    }

    public void setNameLbl(String nameTxt) {
        this.nameLbl.setText(nameTxt);
    }

    public JLabel getWeightLbl() {
        return weightLbl;
    }

    public void setWeightLbl(String weightTxt) {
        this.weightLbl.setText(weightTxt);
    }
}
